/**
 * Hebrew dictionary — source of truth.
 * All strings are the original copy extracted from the Bubble app
 * (see claude_code_pixa_rebuild_prompt.md).
 * Arabic lives in ar.json and is generated by scripts/import-translations.ts.
 */
export const he = {
  common: {
    exit: "יציאה",
    points: "נקודות",
    loading: "טוען...",
  },

  landing: {
    tagline: "המשחק שבו דמיון, יצירתיות ובינה מלאכותית נפגשים",
    subtitle: "הפכו את השיעורים לחוויה לימודית עם בינה מלאכותית",
    purpose:
      "PIXA נועד ללמד תלמידים כיצד לנסח הנחיות מדויקות וברורות לבינה מלאכותית",
    intro:
      "אנחנו חיים בעידן שבו בינה מלאכותית (AI) הופכת לכלי מרכזי בחיינו...",
    howItWorks: "איך המשחק עובד?",
    step1Title: "בחירת תמונות",
    step2Title: "כניסה למשחק",
    step3Title: "פרומפט (הנחיה)",
    step4Title: "משוב והשוואה",
    faqPriorKnowledge: "האם צריך ידע מוקדם ב-AI?",
    faqDuration: "כמה זמן לוקח משחק ממוצע?",
    faqDownload: "האם צריך להוריד משהו לסמארטפון?",
    faqAllClasses: "האם זה מתאים לכל כיתה?",
    faqWhatIsGenerator: "מה זה מחולל תמונות בעזרת בינה מלאכותית?",
    faqCost: "האם המשחק עולה כסף?",
    faqCostAnswer: "לא, המשחק הוא חינמי :)",
    ctaTeachers: "כניסת מורים",
    ctaStudents: "כניסת תלמידים",
    ctaCreateGame: "ליצירת משחק",
    ctaJoinGame: "להצטרף למשחק",
    mobileCreateNote: "יצירת משחק זמינה כרגע במחשב בלבד — תלמידים יכולים להצטרף מהנייד",
  },

  create: {
    welcome: "ברוכים הבאים ל-PIXA!",
    gameSubtitle: "משחק ליצירת תמונה בפרומפט",
    duration: "משך המשחק: בין 15-30 דקות ( תלוי בקצב של הקבוצה)",
    explainCode: "המורה משתף קוד גישה ייחודי למשחק...",
    explainPick:
      "המורה בוחר.ת שתי תמונות מתוך מאגר מוכן מראש או יוצר אותן בעצמו בעזרת בינה מלאכותית בהתאם לנושא השיעור.",
    explainWrite:
      "התלמידים רואים את התמונה הנבחרת על גבי הלוח בכיתה וכותבים פרומפט...",
    explainScore:
      "המערכת משווה בין התמונה שיצרו לתמונה המקורית על סמך 70% התאמה ויזואלית ו-30% התאמה בין הפרומפטים...",
    scanQr: "סרקו את הברקוד והצטרפו ל- PIXA :)",
    joinedPlayers: "משתתפים שהתחברו:",
    startGame: "התחלת המשחק",
    chosenImages: "התמונות הנבחרות:",
    imageBank: "מאגר תמונות",
    customImages: "יצירת תמונות בהתאמה אישית",
    subject: "תחום דעת",
    grade: "כיתה",
    describeImage: "מוזמנים לתאר את התמונה",
    generateImages: "צור את התמונות",
    writeSimilarPrompt: "תכתבו פרומפט שייצר לכם תמונה כמה שיותר דומה לזו",
    matchLevel: "מידת התאמה",
    similarityPct: "% דמיון",
    studentPromptLabel: "הפרומט שהתלמיד כתב:",
    tipLabel: "טיפ לשיפור הפרומט:",
    nextImage: "לתמונה הבאה",
    viewBoard: "צפייה בלוח התלמידים",
  },

  play: {
    joinedSuccess: "התחברת בהצלחה",
    waitForStart: "אנא המתינו עד שהמשחק יתחיל",
    howToWrite: "איך לכתוב פרומט שייצר תמונה זהה:",
    tipAccurate: "להיות מדויקים",
    tipMainDetails: "לתאר את הפרטים המרכזים בתמונה",
    tipSmallDetails: "שימו לב לפרטים הקטנים",
    tipStyle: "ציינו את הסגנון, הצבעים והתאורה שמתאימים לפרומפט",
    describeBoard: "תארו את התמונה שמופיעה על הלוח:",
    generatingFirst: "אנחנו מייצרים את הגרסה הראשונה",
    firstReady: "הגרסה הראשונה מוכנה",
    oneChance: "יש לך הזדמנות אחת לתקן לפני שתקבל ציון",
    improvePrompt: "מוזמנים לשפר את הפרומפט:",
    improvedOnTheWay: "התמונה המשופרת בדרך אליך",
    stepGetScore: "קבלת ציון",
    stepImprove: "שיפור הפרומפט",
    stepCreate: "יצירת תמונה",
    myScore: "הציון שלי: {score} נקודות",
    tipLabel: "טיפ לשיפור הפרומט:",
    exitGame: "יציאה מהמשחק",
    inappropriatePrompt: "יש תוכן לא ראוי בפרומפט, תקן אותו ונסה שוב",
    feedbackQuestion: "באיזה מידה את.ה מרגיש שהשתפרת בכתיבת פרומפטים",
  },

  levels: {
    beginners: "מתחילים",
    beginnersTip: "כאלו שיצרו תמונה או שתיים בעבר",
    advanced: "מתקדמים",
    advancedTip: "כאלו שיצרו במסגרת בית ספר ולמדו על פרומפטים",
    experts: "מומחים",
    expertsTip: "כאלו שהתנסו במשחק כבר ורוצים אתגר משמעותי",
    mine: "התמונות שלי",
  },
} as const;

export type HeDict = typeof he;
